// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyarq1YwzDnDesfTNR2t6RL7kkjrrZyHA',
    appId: '1:666378179002:web:b587270a10a1f1cf618d83',
    messagingSenderId: '666378179002',
    projectId: 'campusconnect-c379f',
    authDomain: 'campusconnect-c379f.firebaseapp.com',
    storageBucket: 'campusconnect-c379f.appspot.com',
    measurementId: 'G-NPVXKJJC4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCriLnaFBxD2rh-lZ-yjOPBmny12XEocqk',
    appId: '1:666378179002:android:8c508da81836cf52618d83',
    messagingSenderId: '666378179002',
    projectId: 'campusconnect-c379f',
    storageBucket: 'campusconnect-c379f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgJWAXRuB9MAf3PRGi4F4xk-yonD9JrFc',
    appId: '1:666378179002:ios:a0ce83e3a9ffc4e7618d83',
    messagingSenderId: '666378179002',
    projectId: 'campusconnect-c379f',
    storageBucket: 'campusconnect-c379f.appspot.com',
    iosClientId: '666378179002-0pinb1c4bobgmp0b41ugs8vmb6ogi9qc.apps.googleusercontent.com',
    iosBundleId: 'com.example.schoolManagmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgJWAXRuB9MAf3PRGi4F4xk-yonD9JrFc',
    appId: '1:666378179002:ios:a0ce83e3a9ffc4e7618d83',
    messagingSenderId: '666378179002',
    projectId: 'campusconnect-c379f',
    storageBucket: 'campusconnect-c379f.appspot.com',
    iosClientId: '666378179002-0pinb1c4bobgmp0b41ugs8vmb6ogi9qc.apps.googleusercontent.com',
    iosBundleId: 'com.example.schoolManagmentApp',
  );
}
